[package]
name = "metalforge-loader"
version = "0.1.0"
edition = "2021"

[dependencies]
metalforge-lib = { path = "../metalforge-lib" }
rockysmithereens_parser = { git = "https://github.com/tversteeg/rockysmithereens.git", features = [ "profile-with-tracing" ] }
hashbrown = "0.15"
url = "2.5.4"